POST {{url}}/participants
Content-Type: application/json

{ "email" : "mitchell22@axoniq.io"}

###
POST {{url}}/objects
Content-Type: application/json

{
  "owner": "6fa9dde3-d2e3-497c-a0bf-eef1e2b49e77",
  "name": "My Awesome object"
}

###
POST {{url}}/auctions
Content-Type: application/json

{
  "objectId": "c218f6a9-c3c0-4289-92cd-491d998f2385",
  "minimumBid": 50.0,
  "duration": 20
}

###
GET {{url}}/auctions/active

###
GET {{url}}/auctions/bb300be7-e4fe-4cc7-963f-a3459ad06b80

###
POST {{url}}/auctions/e3f05b2a-03d3-4eb7-8594-de475137b0da/bid
Content-Type: application/json

{
  "participant": "746aef7f-5954-4868-b9ad-d2f7b51a0852",
  "bid": 2
}

###
GET {{url}}/participants/6fa9dde3-d2e3-497c-a0bf-eef1e2b49e77/auctions

###

GET {{url}}/participants/a33b9311-5f9c-4fe4-beba-4c824440b4d1/bids

###

GET {{url}}/participants/a33b9311-5f9c-4fe4-beba-4c824440b4d1/balance

###
